### ISSUE TITLE
Make scroll behavior to smooth scrolling.

### ISSUE THREAD

**Issue by sebakthapa** [prabeshbastakoti/PiasaTiram#1]
The `scroll-behavior` CSS property is not set to `smooth`. This made the page move to the specified fragments without any scroll animation.
Adding `scroll-behavior: smooth` to the `html` selector would give a nice scrolling animation.

**Comment by prabeshbastakoti** [comment]
@sebakthapa Thank you for your valuable suggestion and contribution. The changes have been made.
